### ISSUE TITLE
Set stop time to None where pickup_type = 1

### ISSUE THREAD

**Issue by linusnorton** [mk-fg/open-track-dtd2mysql-gtfs#1]
With the following diff:

```
[A7ms] API [serw] data mismatch for gtfs trip: GWCTestFailStopNotFound
[A7ms] Trip: <Trip L03198_L02142 [- -] [VIC - CLJ - SRS - ECR - GTW - TBD - HHE - LWS - PLG - HMD - EBN]>
[A7ms] Date/time: 2017-08-19 23:45:00
[A7ms] Diff details:
[A7ms]   Matching journey trip [/tmp/.gtfs-webcheck.api-trip.1nw3yr1b]:
[A7ms]     <Trip L03198_L02142 [2017-08-20 00:05:00 2017-08-20 01:42:00] [VIC - BAK - CLJ - BAL - SRC - SRS - ECR - PUR - RDH - ELD - GTW - TBD - HHE - WVF - LWS - PLG - HMD - EBN]>
[A7ms]   --- /tmp/.gtfs-webcheck.gtfs-trip._7ggu485	2017-08-15 09:33:46.389439518 +0100
[A7ms]   +++ /tmp/.gtfs-webcheck.api-trip.1nw3yr1b	2017-08-15 09:33:46.389439518 +0100
[A7ms]   @@ -1,6 +1,6 @@
[A7ms]    VIC 0:05:00
[A7ms]    CLJ 0:12:00
[A7ms]   -SRS 0:24:00
[A7ms]   +SRS None
[A7ms]    ECR 0:28:00
[A7ms]    GTW 0:46:00
[A7ms]    TBD 0:51:00
```

The association occurs at SRS but passengers are not allowed on or off the train. They've shown this by removing the time (I would too in an API) in the GTFS feed I've put the times but set the pickup_type and drop_off_type to 1 to indicate you can't get on or off. It would be good if you could modify the script to check the treat pickup_type and drop_off_type 1 as a None.

**Comment by linusnorton** [comment]
In fact it may be easiest to ignore stops where they return None as the stop time. If there is no time then it can't be in the GTFS feed

**Comment by mk-fg** [comment]
> In fact it may be easiest to ignore stops where they return None as the stop time.

Yeah, they're actually ignored for the purposes of matching, and only show up in diffs, where I thought it'd be good idea to distinguish "no mention of stop" case from "stop is mentioned as Passing".

Which is why you won't see mismatch where there're only stops without time, which'd have been super-common indeed, as these "passing" stops are returned to draw route on a map, and there's always some of them to draw it more-or-less accurately.

**Comment by linusnorton** [comment]
Ah okay. Do you know why the one above was flagged up as a diff then?

**Comment by mk-fg** [comment]
> treat pickup_type and drop_off_type 1 as a None.

Fairly sure that's already how it's done, but might need to double-check to make sure.

> Ah okay. Do you know why the one above was flagged up as a diff then?

Because gtfs trip has time on the stop, but there's no such stop in API data (only mentioned as "Passing"), as diff shows:

```
[A7ms]   --- /tmp/.gtfs-webcheck.gtfs-trip._7ggu485	2017-08-15 09:33:46.389439518 +0100
[A7ms]   +++ /tmp/.gtfs-webcheck.api-trip.1nw3yr1b	2017-08-15 09:33:46.389439518 +0100
[A7ms]   -SRS 0:24:00
[A7ms]   +SRS None
```

In this particular case, I can't seem to figure out why GTFS has time for that stop at all:
https://gist.github.com/mk-fg/29a01aff01cb33da2927a7c721422065

**Comment by mk-fg** [comment]
> In this particular case, I can't seem to figure out why GTFS has time for that stop at all:

E.g. look up (Ctrl+F/grep) "SRS" in that diff - CIF has no public time for any of them (displayed as --:--), but stop_time in GTFS is set for some reason...

**Comment by mk-fg** [comment]
Oh, now looking at that stop sequence, think I misunderstood what you meant above.

You mean dropping GTFS trip stops that have both pickup/dropoff = none, which apparently is not done for SRS, while I misread it as doing that for stops returned from API (the one with None in that diff).

Will fix in a moment.

**Comment by mk-fg** [comment]
Fixed in 252dc5e.

Same trip apparently has one other diff on e.g. 2017-10-29:
```
[sFn-] API [serw] data mismatch for gtfs trip: GWCTestFailStopMismatch
[sFn-] Trip: <Trip L03198_L02142 [- -] [VIC - CLJ - ECR - GTW - TBD - HHE - LWS - PLG - HMD - EBN]>
[sFn-] Date/time: 2017-10-28 23:45:00
[sFn-] Diff details:
[sFn-]   Matching journey trip [/tmp/.gtfs-webcheck.api-trip.qnu9h5qf]:
[sFn-]     <Trip L03198_L02142 [2017-10-29 00:05:00 2017-10-29 01:48:00] [VIC - BAK - CLJ - BAL - SRC - SRS - ECR - SCY - PUR - RDH - ELD - GTW - TBD - HHE - W
VF - LWS - PLG - HMD - EBN]>
[sFn-]   --- /tmp/.gtfs-webcheck.gtfs-trip.a8kuodrm     2017-08-16 12:46:09.223758872 +0500
[sFn-]   +++ /tmp/.gtfs-webcheck.api-trip.qnu9h5qf      2017-08-16 12:46:09.224758854 +0500
[sFn-]   @@ -4,7 +4,7 @@
[sFn-]    GTW 0:46:00
[sFn-]    TBD 0:51:00
[sFn-]    HHE 1:06:00
[sFn-]   -LWS 1:21:00
[sFn-]   -PLG 1:33:00
[sFn-]   -HMD 1:37:00
[sFn-]   -EBN 1:42:00
[sFn-]   +LWS 1:27:00
[sFn-]   +PLG 1:39:00
[sFn-]   +HMD 1:43:00
[sFn-]   +EBN 1:48:00
```

**Comment by mk-fg** [comment]
> Same trip apparently has one other diff on e.g. 2017-10-29:

Seeing how times differ by a small margin there, actually reminds me of a thing I should've mentioned earlier - there's "test_trip_time_slack" tunable set to 5 minutes which would usually skip time diffs smaller than that (e.g. pickup/dropoff times offset by minute).
Makes me wonder if it was a mistake and should be disabled entirely, to have more strict checks as "either data match completely or it does not".

**Comment by linusnorton** [comment]
Until we can think of there being a legitimate reason for discrepancies maybe we should turn it off otherwise it may mask problems with overlays.

**Comment by mk-fg** [comment]
Done.
